/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Source file was org.bluez.Battery1.xml
 *
 * qdbusxml2cpp is Copyright (C) The Qt Company Ltd. and other contributors.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef BATTERY1_P_H
#define BATTERY1_P_H

//
//  W A R N I N G
//  -------------
//
// This file is not part of the Qt API.  It exists purely as an
// implementation detail.  This header file may change from version to
// version without notice, or even be removed.
//
// We mean it.
//

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include <QtCore/private/qglobal_p.h>

namespace QtBluetoothPrivate {

/*
 * Proxy class for interface org.bluez.Battery1
 */
class OrgBluezBattery1Interface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.bluez.Battery1"; }

public:
    OrgBluezBattery1Interface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = nullptr);

    ~OrgBluezBattery1Interface();

    Q_PROPERTY(uchar Percentage READ percentage)
    inline uchar percentage() const
    { return qvariant_cast< uchar >(property("Percentage")); }

public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
};

} // end of namespace QtBluetoothPrivate

namespace org {
  namespace bluez {
    using Battery1 = ::QtBluetoothPrivate::OrgBluezBattery1Interface;
  }
}

#endif
