/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a leadvertisement1_p.h:leadvertisement1.cpp -i bluez5_helper_p.h org.bluez.LEAdvertisement1.xml
 *
 * qdbusxml2cpp is Copyright (C) 2022 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "leadvertisement1_p.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class LEAdvertisement1Adaptor
 */

LEAdvertisement1Adaptor::LEAdvertisement1Adaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

LEAdvertisement1Adaptor::~LEAdvertisement1Adaptor()
{
    // destructor
}

QStringList LEAdvertisement1Adaptor::includes() const
{
    // get the value of property Includes
    return qvariant_cast< QStringList >(parent()->property("Includes"));
}

void LEAdvertisement1Adaptor::setIncludes(const QStringList &value)
{
    // set the value of property Includes
    parent()->setProperty("Includes", QVariant::fromValue(value));
}

QString LEAdvertisement1Adaptor::localName() const
{
    // get the value of property LocalName
    return qvariant_cast< QString >(parent()->property("LocalName"));
}

void LEAdvertisement1Adaptor::setLocalName(const QString &value)
{
    // set the value of property LocalName
    parent()->setProperty("LocalName", QVariant::fromValue(value));
}

ManufacturerDataList LEAdvertisement1Adaptor::manufacturerData() const
{
    // get the value of property ManufacturerData
    return qvariant_cast< ManufacturerDataList >(parent()->property("ManufacturerData"));
}

void LEAdvertisement1Adaptor::setManufacturerData(ManufacturerDataList value)
{
    // set the value of property ManufacturerData
    parent()->setProperty("ManufacturerData", QVariant::fromValue(value));
}

QStringList LEAdvertisement1Adaptor::serviceUUIDs() const
{
    // get the value of property ServiceUUIDs
    return qvariant_cast< QStringList >(parent()->property("ServiceUUIDs"));
}

void LEAdvertisement1Adaptor::setServiceUUIDs(const QStringList &value)
{
    // set the value of property ServiceUUIDs
    parent()->setProperty("ServiceUUIDs", QVariant::fromValue(value));
}

QString LEAdvertisement1Adaptor::type() const
{
    // get the value of property Type
    return qvariant_cast< QString >(parent()->property("Type"));
}

void LEAdvertisement1Adaptor::setType(const QString &value)
{
    // set the value of property Type
    parent()->setProperty("Type", QVariant::fromValue(value));
}

void LEAdvertisement1Adaptor::Release()
{
    // handle method call org.bluez.LEAdvertisement1.Release
    QMetaObject::invokeMethod(parent(), "Release");
}

