/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Source file was org.bluez.Profile1.xml
 *
 * qdbusxml2cpp is Copyright (C) The Qt Company Ltd. and other contributors.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "profile1_p.h"

namespace QtBluetoothPrivate {

/*
 * Implementation of interface class OrgBluezProfile1Interface
 */

OrgBluezProfile1Interface::OrgBluezProfile1Interface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgBluezProfile1Interface::~OrgBluezProfile1Interface()
{
}

} // end of namespace QtBluetoothPrivate

#include "moc_profile1_p.cpp"
