/* This file was generated by syncqt with the info from sync.profile. */
#ifndef QT_QTBLUETOOTH_VERSION_H
#define QT_QTBLUETOOTH_VERSION_H

#define QTBLUETOOTH_VERSION_STR "5.0.0"

#define QTBLUETOOTH_VERSION 0x050000

#endif // QT_QTBLUETOOTH_VERSION_H
