/* This file was generated by syncqt with the info from sync.profile. */
#ifndef QT_QTNFC_VERSION_H
#define QT_QTNFC_VERSION_H

#define QTNFC_VERSION_STR "5.0.0"

#define QTNFC_VERSION 0x050000

#endif // QT_QTNFC_VERSION_H
